# Generated by Django 4.0 on 2022-01-17 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added+by+', to='auth.user')),
            ],
        ),
    ]
