# Generated by Django 4.0 on 2022-01-17 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filesadmin',
            old_name='users',
            new_name='user',
        ),
    ]
