# Generated by Django 4.0 on 2022-01-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_alter_filesadmin_adminupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesadmin',
            name='adminupload',
            field=models.FileField(upload_to='media'),
        ),
    ]
