# Generated by Django 4.0 on 2022-01-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_alter_filesadmin_adminupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesadmin',
            name='adminupload',
            field=models.FileField(default='C:/abcd/internprog/image_certificate/cert.jpg', upload_to='media'),
        ),
    ]
