# Generated by Django 4.0 on 2022-01-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_remove_filesadmin_adminupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesadmin',
            name='adminupload',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
