# Generated by Django 4.0 on 2022-01-01 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0007_filesadmin_adminupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filesadmin',
            name='adminupload',
        ),
    ]
