# Generated by Django 4.0 on 2022-01-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0008_remove_filesadmin_adminupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesadmin',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
